#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_GPL)
#

apps-$(CONFIG_APP_SEL4BENCH) += sel4bench

sel4bench-y = common libsel4 $(libc) libsel4vka libsel4allocman \
           libsel4utils libsel4platsupport libsel4muslcsys libsel4bench libplatsupport libelf libcpio libsel4debug \
           libsel4benchsupport libsel4debug libjansson

sel4bench-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default

# benchmarking apps that this app depends on
sel4bench-components-$(CONFIG_APP_IPCBENCH) += ipc
sel4bench-components-$(CONFIG_APP_IRQBENCH) += irq
sel4bench-components-$(CONFIG_APP_IRQUSERBENCH) += irquser
sel4bench-components-$(CONFIG_APP_SCHEDULERBENCH) += scheduler
sel4bench-components-$(CONFIG_APP_SIGNALBENCH) += signal
sel4bench-components-$(CONFIG_APP_FAULTBENCH) += fault
sel4bench-components-$(CONFIG_APP_HARDWAREBENCH) += hardware
sel4bench-components-$(CONFIG_APP_SYNCBENCH) += sync
sel4bench-components-$(CONFIG_APP_PAGEMAPPINGBENCH) += page_mapping
sel4bench-components-$(CONFIG_APP_SMPBENCH) += smp

sel4bench-components = $(addprefix $(STAGE_BASE)/bin/, $(sel4bench-components-y))

sel4bench: export COMPONENTS=${sel4bench-components}
sel4bench: ${sel4bench-components-y} kernel_elf $(sel4bench-y)

