#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_SEL4BENCH) += sel4bench

sel4bench-y = common libsel4 $(libc) libsel4vka libsel4allocman \
           libsel4utils libsel4platsupport libsel4muslcsys libsel4bench libplatsupport libelf libcpio

ifdef CONFIG_KERNEL_STABLE
sel4bench-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
sel4bench-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

sel4bench: kernel_elf $(sel4bench-y)
