#
# Copyright 2016, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

components-$(CONFIG_APP_TIMEOUTBENCH) += timeout
timeout: common libsel4 $(libc) libsel4vka libsel4allocman libsel4bench \
           libsel4utils libsel4bench libsel4simple libsel4muslcsys \
           libsel4platsupport libplatsupport libsel4vspace libsel4benchsupport \
           libsel4debug


