#
# Copyright 2016, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(D61_BSD)
#

components-$(CONFIG_APP_SYNCBENCH) += sync
sync: common libsel4 $(libc) libsel4vka libsel4allocman libsel4bench \
           libsel4utils libsel4bench libsel4simple libsel4muslcsys \
           libsel4platsupport libplatsupport libsel4vspace libsel4benchsupport \
           libsel4debug


