#
# Copyright 2016, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

libs-$(CONFIG_LIB_SEL4_BENCHSUPPORT) += libsel4benchsupport
libsel4benchsupport: libsel4vka libsel4vspace libsel4allocman libsel4 common $(libc) libutils
