#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

libs-$(CONFIG_LIB_SEL4_BENCHSUPPORT) += libsel4benchsupport
libsel4benchsupport: libsel4vka libsel4vspace libsel4allocman libsel4 common $(libc) libutils libsel4debug \
                     libplatsupport libsel4platsupport libsel4serialserver libsel4bench
